// CONFIG TYPES
const SET_WORKS = 'SET_WORKS';
const SET_IS_DATA_LOADED = 'SET_IS_DATA_LOADED';

// FILTER TYPES
const GET_WORK_LIST = 'GET_WORK_LIST';
const GET_WORK_BY_ID = 'GET_WORK_BY_ID';

export { SET_WORKS, GET_WORK_LIST, GET_WORK_BY_ID, SET_IS_DATA_LOADED };
