// CONFIG TYPES
const SET_WORKS = 'SET_WORKS';
const SET_IS_DATA_LOADED = 'SET_IS_DATA_LOADED';

// FILTER TYPES
const FILTER_BY_ID = 'FILTER_BY_ID';

export { SET_WORKS, SET_IS_DATA_LOADED, FILTER_BY_ID };
